name: Execute Windows and Linux (x86, x64) Tests with Intel SDE Processors

env:
  SDE_WINDOWS_URL: https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
  SDE_LINUX_URL: https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-lin.tar.xz

on:
  workflow_dispatch:

jobs:
  # build:
  #   uses: ./.github/workflows/windows-and-linux-build.yml

  test-sde:
    strategy:
      matrix:
        arch: [windows-x86, windows-x64, linux-x86_64]
        sde-processor: [skl]
    runs-on: ${{ matrix.arch == 'linux-x86_64' && 'ubuntu-latest' || 'windows-latest' }}
    #needs: build
    timeout-minutes: 60
    continue-on-error: true

    steps:
      # - name: Download Build Artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-artifacts-${{ matrix.arch }}
      #     path: build/${{ matrix.arch }}/

      - name: Download Intel SDE
        run: |
          if [ "${{ matrix.arch }}" == "linux-x86_64" ]; then
            echo "Downloading Linux Intel SDE"
            wget "$SDE_LINUX_URL" && tar -xf "$(basename "$SDE_LINUX_URL")"
          elif [[ "${{ matrix.arch }}" == "windows-x86" || "${{ matrix.arch }}" == "windows-x64" ]]; then
            echo "Downloading Windows Intel SDE"
            curl -LO "$SDE_WINDOWS_URL" && tar -xf "$(basename "$SDE_WINDOWS_URL")" 
          fi
        shell: bash

      - name: Set SDE PATH
        run: |
          if [ "${{ matrix.arch }}" == "linux-x86_64" ]; then
            SDE_DIR="$(basename "$SDE_LINUX_URL" | sed 's/.tar.xz//')"
          elif [[ "${{ matrix.arch }}" == "windows-x86" || "${{ matrix.arch }}" == "windows-x64" ]]; then
            SDE_DIR="$(basename "$SDE_WINDOWS_URL" | sed 's/.tar.xz//')"
          fi
          SDE_PATH="${{ github.workspace }}/${SDE_DIR}/sde"
          echo "SDE_PATH=$SDE_PATH" >> $GITHUB_ENV && echo "SDE_PATH set to: $SDE_PATH"
        shell: bash

      - name: Run tests using Intel SDE (Linux)
        if: matrix.arch == 'linux-x86_64'
        run: |
          $SDE_PATH -help
        #working-directory: ${{ github.workspace }}/build/${{ matrix.arch }}
        shell: bash

      - name: Run tests using Intel SDE (Windows-x86 and Windows-x64)
        if: matrix.arch == 'windows-x86' || matrix.arch == 'windows-x64'
        run: |
          & "$env:SDE_PATH" -help
        #working-directory: ${{ github.workspace }}/build/${{ matrix.arch }}
        shell: pwsh